FROM docker.io/pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel

RUN apt update && apt install -y git

RUN pip uninstall -y transformers peft

RUN pip install git+https://github.com/huggingface/transformers \
    git+https://github.com/huggingface/peft \
    accelerate \
    scikit-learn \
    evaluate \
    torchvision \
    Pillow \
    qwen-vl-utils==0.0.14 \
    bitsandbytes==0.48.2

RUN pip install flash-attn==2.7.4.post1 --no-build-isolation
RUN pip install liger-kernel

RUN mkdir /.cache && chmod 777 /.cache