FROM docker.io/pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel

COPY requirements.txt /

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

RUN pip3 install transformers==4.57.1 accelerate==1.11.0 safetensors tokenizers

RUN pip install -r /requirements.txt

RUN pip install qwen-vl-utils==0.0.14 bitsandbytes==0.48.2

RUN pip install https://github.com/deepseek-ai/DeepSeek-VL/archive/refs/heads/main.zip

RUN pip install flash-attn==2.7.4.post1 --no-build-isolation

RUN mkdir /.cache && chmod 777 /.cache